import { useState, useEffect } from 'react';
import type { ChangeEvent } from 'react';
import { 
  BookOpen, 
  Sparkles, 
  Wand2, 
  RefreshCw, 
  Key, 
  Download, 
  ArrowLeft, 
  ArrowRight, 
  Trash2, 
  Edit2, 
  Check, 
  Plus, 
  FileText, 
  HelpCircle,
  AlertCircle
} from 'lucide-react';
import { generateStory, generateImage, searchLexicaImage } from './gemini';
import type { StoryConfig, StoryPage, GeneratedBook } from './gemini';
import { saveBookDB, getBooksDB, deleteBookDB } from './db';

interface BookWithMetadata extends GeneratedBook {
  id: string;
  createdAt: string;
  config: StoryConfig;
  seeds: number[]; // seeds for each page to persist images
  images?: string[]; // base64 images generated by Gemini
  timestamp?: number; // timestamp for sorting
}

const THEME_OPTIONS = [
  { id: 'Fantasy', label: 'Fantasy 🪄', icon: '🪄', promptStyle: 'magical watercolor illustration, children\'s book art, soft lighting, vibrant colors' },
  { id: 'Sci-Fi', label: 'Sci-Fi 🚀', icon: '🚀', promptStyle: 'dreamy retro-futuristic digital painting, soft glow, children\'s sci-fi illustration' },
  { id: 'Mystery', label: 'Mystery 🕵️‍♂️', icon: '🕵️‍♂️', promptStyle: 'cozy mystery watercolor, warm candlelight, detailed children\'s book illustration' },
  { id: 'Fairy Tale', label: 'Fairy Tale 🏰', icon: '🏰', promptStyle: 'enchanted storybook illustration, gold leaf details, whimsical pastel colors' },
  { id: 'Custom', label: 'Custom 🎨', icon: '🎨', promptStyle: 'beautiful digital children\'s illustration' },
];

export default function App() {
  // API Key State
  const [apiKey, setApiKey] = useState<string>('');
  const [showKeyModal, setShowKeyModal] = useState<boolean>(false);
  const [tempKey, setTempKey] = useState<string>('');

  // Setup Wizard State
  const [theme, setTheme] = useState<string>('Fantasy');
  const [customStyle, setCustomStyle] = useState<string>('');
  const [protagonistName, setProtagonistName] = useState<string>('Leo');
  const [protagonistDescription, setProtagonistDescription] = useState<string>('A brave little lion cub with a fluffy, golden mane and green eyes');
  const [companionName, setCompanionName] = useState<string>('Pip');
  const [companionDescription, setCompanionDescription] = useState<string>('A tiny bluebird who always carries a satchel of glittering star dust');
  const [specialTool, setSpecialTool] = useState<string>('A glowing star lantern');
  const [pagesCount, setPagesCount] = useState<number>(5);
  const [tone, setTone] = useState<string>('Whimsical');
  const [ageGroup, setAgeGroup] = useState<string>('6-8 years');
  const [model, setModel] = useState<string>('gemini-2.5-flash');
  const [imageGenerator, setImageGenerator] = useState<'gemini' | 'lexica' | 'pollinations'>('lexica');
  const [illustrationStyle, setIllustrationStyle] = useState<'fairy' | 'simple_strokes'>('fairy');

  // App States
  const [loading, setLoading] = useState<boolean>(false);
  const [loadingStep, setLoadingStep] = useState<string>('');
  const [error, setError] = useState<string | null>(null);
  
  // Library and Current Book States
  const [library, setLibrary] = useState<BookWithMetadata[]>([]);
  const [currentBook, setCurrentBook] = useState<BookWithMetadata | null>(null);
  const [currentPageIndex, setCurrentPageIndex] = useState<number>(0);
  
  // Image states
  const [imageLoading, setImageLoading] = useState<boolean>(false);
  const [imageError, setImageError] = useState<boolean>(false);
  
  // Editor States
  const [isEditing, setIsEditing] = useState<boolean>(false);
  const [editedText, setEditedText] = useState<string>('');
  const [editedPrompt, setEditedPrompt] = useState<string>('');

  // Load API Key & Library on startup
  useEffect(() => {
    const savedKey = localStorage.getItem('gemini_api_key');
    if (savedKey) {
      setApiKey(savedKey);
      setTempKey(savedKey);
    } else {
      setShowKeyModal(true);
    }

    const loadLibrary = async () => {
      try {
        let books = await getBooksDB();
        
        // Migration from localStorage if needed
        const savedBooks = localStorage.getItem('adventure_books');
        if (savedBooks && books.length === 0) {
          const parsed = JSON.parse(savedBooks);
          if (Array.isArray(parsed) && parsed.length > 0) {
            for (const b of parsed) {
              await saveBookDB({
                ...b,
                timestamp: b.timestamp || Date.now()
              });
            }
            books = await getBooksDB();
            localStorage.removeItem('adventure_books');
          }
        }
        
        // Sort books by timestamp desc (newest first)
        books.sort((a, b) => (b.timestamp || 0) - (a.timestamp || 0));
        setLibrary(books);
      } catch (e) {
        console.error('Failed to load books database', e);
      }
    };
    loadLibrary();
  }, []);

  // Reset image error state on page change
  useEffect(() => {
    setImageError(false);
  }, [currentPageIndex, currentBook?.id]);

  // Save key
  const handleSaveKey = (key: string) => {
    const trimmed = key.trim();
    localStorage.setItem('gemini_api_key', trimmed);
    setApiKey(trimmed);
    setShowKeyModal(false);
  };

  // Clear key
  const handleClearKey = () => {
    localStorage.removeItem('gemini_api_key');
    setApiKey('');
    setTempKey('');
    setShowKeyModal(true);
  };

  // Generate Book Action
  const handleGenerateBook = async () => {
    if (!apiKey) {
      setShowKeyModal(true);
      return;
    }

    setLoading(true);
    setError(null);
    setLoadingStep('Consulting the wizarding scribe (Connecting to Gemini)...');

    const config: StoryConfig = {
      theme,
      protagonistName,
      protagonistDescription,
      companionName: companionName ? companionName : undefined,
      companionDescription: companionDescription ? companionDescription : undefined,
      specialTool: specialTool ? specialTool : undefined,
      pagesCount,
      tone,
      ageGroup,
      illustrationStyle
    };

    try {
      setLoadingStep('Drafting the adventure blueprint...');
      const responseBook = await generateStory(apiKey, config, model);

      // Generate random seed for each page
      const seeds = Array.from({ length: responseBook.pages.length }, () => 
        Math.floor(Math.random() * 1000000)
      );

      const selectedTheme = THEME_OPTIONS.find(t => t.id === theme);
      const styleSuffix = illustrationStyle === 'simple_strokes'
        ? 'minimalist simple black ink outline sketch on a clean solid white background, cute childlike marker doodle style, simple strokes, black ink on white paper, no color, no background detail'
        : (selectedTheme ? selectedTheme.promptStyle : (customStyle || 'children\'s book illustration'));

      const images: string[] = [];
      if (imageGenerator === 'gemini') {
        for (let i = 0; i < responseBook.pages.length; i++) {
          setLoadingStep(`Painting illustration for page ${i + 1} of ${responseBook.pages.length}...`);
          const page = responseBook.pages[i];
          try {
            const imgData = await generateImage(apiKey, `${page.illustrationPrompt}, ${styleSuffix}`);
            images.push(imgData);
          } catch (e: any) {
            console.error(`Failed to generate image for page ${i + 1}`, e);
            images.push('');
          }
        }
      } else if (imageGenerator === 'lexica') {
        for (let i = 0; i < responseBook.pages.length; i++) {
          setLoadingStep(`Finding matching illustration for page ${i + 1} of ${responseBook.pages.length}...`);
          const page = responseBook.pages[i];
          try {
            const imgUrl = await searchLexicaImage(`${page.illustrationPrompt}, ${styleSuffix}`);
            images.push(imgUrl);
          } catch (e: any) {
            console.error(`Failed to search Lexica image for page ${i + 1}`, e);
            images.push('');
          }
        }
      }

      const newBook: BookWithMetadata = {
        ...responseBook,
        id: crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).substring(2, 9),
        createdAt: new Date().toLocaleDateString(),
        config,
        seeds,
        images: (imageGenerator === 'gemini' || imageGenerator === 'lexica') ? images : undefined,
        timestamp: Date.now()
      };

      // Save to library DB
      await saveBookDB(newBook);
      const updatedLibrary = [newBook, ...library];
      setLibrary(updatedLibrary);

      // Display the book
      setCurrentBook(newBook);
      setCurrentPageIndex(0);
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'An unexpected error occurred. Please verify your API Key and network connection.');
    } finally {
      setLoading(false);
    }
  };

  // Re-roll image seed (regenerate illustration)
  const handleRerollImage = async () => {
    if (!currentBook) return;

    const selectedTheme = THEME_OPTIONS.find(t => t.id === currentBook.config.theme);
    const styleSuffix = currentBook.config.illustrationStyle === 'simple_strokes'
      ? 'minimalist simple black ink outline sketch on a clean solid white background, cute childlike marker doodle style, simple strokes, black ink on white paper, no color, no background detail'
      : (selectedTheme ? selectedTheme.promptStyle : (customStyle || 'children\'s book illustration'));

    if (imageGenerator === 'gemini') {
      if (!apiKey) {
        setShowKeyModal(true);
        return;
      }
      setImageLoading(true);
      try {
        const page = currentBook.pages[currentPageIndex];
        const newImgData = await generateImage(apiKey, `${page.illustrationPrompt}, ${styleSuffix}`);
        
        const updatedImages = currentBook.images ? [...currentBook.images] : Array(currentBook.pages.length).fill('');
        updatedImages[currentPageIndex] = newImgData;
        
        const updatedBook = {
          ...currentBook,
          images: updatedImages
        };
        
        await updateBookInLibrary(updatedBook);
      } catch (e: any) {
        console.error(e);
        alert(e.message || 'Failed to regenerate image with Gemini.');
      } finally {
        setImageLoading(false);
      }
    } else if (imageGenerator === 'lexica') {
      setImageLoading(true);
      try {
        const page = currentBook.pages[currentPageIndex];
        const newImgUrl = await searchLexicaImage(`${page.illustrationPrompt}, ${styleSuffix}`);
        
        const updatedImages = currentBook.images ? [...currentBook.images] : Array(currentBook.pages.length).fill('');
        updatedImages[currentPageIndex] = newImgUrl;
        
        const updatedBook = {
          ...currentBook,
          images: updatedImages
        };
        
        await updateBookInLibrary(updatedBook);
      } catch (e: any) {
        console.error(e);
        alert(e.message || 'Failed to find image with Lexica.');
      } finally {
        setImageLoading(false);
      }
    } else {
      const updatedSeeds = [...currentBook.seeds];
      updatedSeeds[currentPageIndex] = Math.floor(Math.random() * 1000000);
      
      const updatedBook = {
        ...currentBook,
        seeds: updatedSeeds
      };

      await updateBookInLibrary(updatedBook);
    }
  };

  // Update book in library and current state
  const updateBookInLibrary = async (updatedBook: BookWithMetadata) => {
    setCurrentBook(updatedBook);
    try {
      await saveBookDB(updatedBook);
      const updatedLibrary = library.map(b => b.id === updatedBook.id ? updatedBook : b);
      setLibrary(updatedLibrary);
    } catch (e) {
      console.error('Failed to update book', e);
    }
  };

  // Save manual edits to text or prompts
  const handleSaveChanges = async () => {
    if (!currentBook) return;
    const updatedPages = [...currentBook.pages];
    updatedPages[currentPageIndex] = {
      ...updatedPages[currentPageIndex],
      storyText: editedText,
      illustrationPrompt: editedPrompt
    };

    const updatedBook = {
      ...currentBook,
      pages: updatedPages
    };

    await updateBookInLibrary(updatedBook);
    setIsEditing(false);
  };

  // Enter editing mode
  const startEditing = () => {
    if (!currentBook) return;
    const currentPage = currentBook.pages[currentPageIndex];
    setEditedText(currentPage.storyText);
    setEditedPrompt(currentPage.illustrationPrompt);
    setIsEditing(true);
  };

  // Delete Book
  const handleDeleteBook = async (id: string) => {
    if (confirm('Are you sure you want to delete this adventure forever?')) {
      try {
        await deleteBookDB(id);
        const updatedLibrary = library.filter(b => b.id !== id);
        setLibrary(updatedLibrary);
        if (currentBook?.id === id) {
          setCurrentBook(null);
        }
      } catch (e) {
        console.error('Failed to delete book', e);
      }
    }
  };

  // Export Book to HTML File
  const handleExportHtml = () => {
    if (!currentBook) return;

    const bookPagesHtml = currentBook.pages.map((page, idx) => {
      const selectedTheme = THEME_OPTIONS.find(t => t.id === currentBook.config.theme);
      const styleSuffix = selectedTheme ? selectedTheme.promptStyle : 'children\'s book illustration';
      const imageUrl = currentBook.images && currentBook.images[idx]
        ? currentBook.images[idx]
        : `https://image.pollinations.ai/prompt/${encodeURIComponent(page.illustrationPrompt + ', ' + styleSuffix)}?width=800&height=600&nologo=true&seed=${currentBook.seeds[idx]}`;

      return `
        <div class="page-container">
          <div class="book-card">
            <div class="image-side">
              <img src="${imageUrl}" alt="Illustration for page ${idx + 1}" />
            </div>
            <div class="text-side">
              <div class="story-content">${page.storyText}</div>
              <div class="page-footer">Page ${idx + 1}</div>
            </div>
          </div>
        </div>
      `;
    }).join('');

    const htmlContent = `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${currentBook.title} - Adventure Book</title>
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;1,400&family=Outfit:wght@400;600&display=swap" rel="stylesheet">
        <style>
          body {
            background-color: #0c0f1d;
            font-family: 'Outfit', sans-serif;
            color: #f8fafc;
            margin: 0;
            padding: 40px 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
          }
          h1 {
            font-family: 'Playfair Display', serif;
            font-size: 3rem;
            text-align: center;
            margin-bottom: 40px;
            background: linear-gradient(135deg, #f8fafc 30%, #a5b4fc 70%, #ec4899 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
          }
          .page-container {
            width: 100%;
            max-width: 1000px;
            margin-bottom: 60px;
            page-break-after: always;
          }
          .book-card {
            display: grid;
            grid-template-columns: 1.2fr 1fr;
            background: #fdfbf7;
            border-radius: 16px;
            overflow: hidden;
            box-shadow: 0 20px 40px rgba(0,0,0,0.5);
            border: 6px solid #3e2723;
            color: #2d2a26;
            min-height: 500px;
          }
          @media (max-width: 768px) {
            .book-card {
              grid-template-columns: 1fr;
            }
          }
          .image-side {
            background-color: #e2e8f0;
            display: flex;
            align-items: center;
            justify-content: center;
          }
          .image-side img {
            width: 100%;
            height: 100%;
            object-fit: cover;
            display: block;
          }
          .text-side {
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            padding: 40px;
            background: linear-gradient(to right, #f7f3eb 0%, #fdfbf7 8%, #fdfbf7 100%);
          }
          .story-content {
            font-family: 'Playfair Display', serif;
            font-size: 1.4rem;
            line-height: 1.7;
            color: #3a3530;
          }
          .page-footer {
            font-family: 'Playfair Display', serif;
            font-style: italic;
            font-size: 1rem;
            color: #8b8070;
            text-align: center;
            margin-top: 20px;
            border-top: 1px dashed rgba(0,0,0,0.1);
            padding-top: 10px;
          }
          .no-print-header {
            margin-bottom: 20px;
            display: flex;
            gap: 10px;
          }
          button {
            background: #6366f1;
            border: none;
            color: white;
            padding: 10px 20px;
            font-weight: 600;
            border-radius: 6px;
            cursor: pointer;
          }
          @media print {
            body { background: #fff !important; color: #000; padding: 0; }
            .no-print-header { display: none !important; }
            .book-card { box-shadow: none !important; border: none !important; }
          }
        </style>
      </head>
      <body>
        <div class="no-print-header">
          <button onclick="window.print()">Print to PDF</button>
        </div>
        <h1>${currentBook.title}</h1>
        ${bookPagesHtml}
      </body>
      </html>
    `;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${currentBook.title.replace(/\s+/g, '_')}_adventure.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Export entire library to JSON file
  const handleExportLibraryJSON = () => {
    if (library.length === 0) {
      alert("No books in library to export.");
      return;
    }
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(library, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `adventure_forge_library_${new Date().toISOString().slice(0, 10)}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    document.body.removeChild(downloadAnchor);
  };

  // Import library from JSON file
  const handleImportLibraryJSON = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async (e) => {
      try {
        const imported = JSON.parse(e.target?.result as string);
        if (!Array.isArray(imported)) {
          throw new Error("Imported file is not a valid library array.");
        }
        
        setLoading(true);
        setLoadingStep("Importing stories into library...");
        
        let count = 0;
        for (const book of imported) {
          if (book.title && book.pages && book.config) {
            // Verify if book already exists in library to avoid duplication
            if (!library.some(b => b.id === book.id)) {
              await saveBookDB(book);
              count++;
            }
          }
        }
        
        // Reload library from IndexedDB
        const updated = await getBooksDB();
        setLibrary(updated);
        
        alert(`Successfully imported ${count} new book(s) into your library!`);
      } catch (err: any) {
        console.error(err);
        alert("Failed to import library: " + err.message);
      } finally {
        setLoading(false);
      }
    };
    reader.readAsText(file);
  };

  // Get current page illustration image URL
  const getImageUrl = (page: StoryPage, idx: number) => {
    if (!currentBook) return '';
    if (currentBook.images && currentBook.images[idx]) {
      return currentBook.images[idx];
    }
    const selectedTheme = THEME_OPTIONS.find(t => t.id === currentBook.config.theme);
    const styleSuffix = currentBook.config.illustrationStyle === 'simple_strokes'
      ? 'minimalist simple black ink outline sketch on a clean solid white background, cute childlike marker doodle style, simple strokes, black ink on white paper, no color, no background detail'
      : (selectedTheme ? selectedTheme.promptStyle : (customStyle || 'children\'s book illustration'));
    
    return `https://image.pollinations.ai/prompt/${encodeURIComponent(page.illustrationPrompt + ', ' + styleSuffix)}?width=700&height=600&nologo=true&seed=${currentBook.seeds[idx]}`;
  };

  return (
    <div className="container">
      {/* App Header */}
      <header className="app-header no-print">
        <div className="app-title-container">
          <BookOpen className="app-title-icon" size={32} />
          <span className="app-logo text-gradient">AdventureForge</span>
        </div>
        
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <button 
            className="btn btn-secondary" 
            onClick={() => {
              if (apiKey) {
                handleClearKey();
              } else {
                setShowKeyModal(true);
              }
            }}
            title={apiKey ? "Clear Gemini API Key" : "Configure Gemini API Key"}
            style={{ padding: '8px 16px', fontSize: '0.9rem' }}
          >
            <Key size={16} />
            {apiKey ? 'Clear Key' : 'Setup API Key'}
          </button>
          
          {currentBook && (
            <button 
              className="btn btn-primary" 
              onClick={() => setCurrentBook(null)}
              style={{ padding: '8px 16px', fontSize: '0.9rem' }}
            >
              <Plus size={16} />
              New Book
            </button>
          )}
        </div>
      </header>

      {/* Main Content Area */}
      <main>
        {/* Loading Spinner */}
        {loading && (
          <div className="glass-panel" style={{ padding: '60px 40px', textAlign: 'center', margin: '40px auto', maxWidth: '600px' }}>
            <div style={{ position: 'relative', width: '80px', height: '80px', margin: '0 auto 24px' }}>
              <div style={{
                boxSizing: 'border-box',
                display: 'block',
                position: 'absolute',
                width: '64px',
                height: '64px',
                margin: '8px',
                border: '8px solid var(--primary)',
                borderRadius: '50%',
                animation: 'loading-spin 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite',
                borderColor: 'var(--primary) transparent transparent transparent'
              }}></div>
            </div>
            <h3 style={{ fontSize: '1.4rem', marginBottom: '12px' }}>Weaving Magic...</h3>
            <p style={{ color: 'var(--text-secondary)' }}>{loadingStep}</p>
            <style>{`
              @keyframes loading-spin {
                0% { transform: rotate(0deg); }
                100% { transform: rotate(360deg); }
              }
            `}</style>
          </div>
        )}

        {/* Error Alert */}
        {error && !loading && (
          <div className="glass-panel" style={{ padding: '24px', borderColor: '#ef4444', backgroundColor: 'rgba(239, 68, 68, 0.08)', margin: '20px 0', display: 'flex', gap: '16px', alignItems: 'center' }}>
            <AlertCircle size={28} style={{ color: '#ef4444', flexShrink: 0 }} />
            <div>
              <h4 style={{ color: '#ef4444', fontWeight: 600, marginBottom: '4px' }}>Wizarding Error</h4>
              <p style={{ fontSize: '0.95rem', color: 'var(--text-primary)' }}>{error}</p>
            </div>
          </div>
        )}

        {/* BOOK READER VIEW */}
        {currentBook && !loading && (
          <div>
            <div className="no-print" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
              <button 
                className="btn btn-secondary" 
                onClick={() => setCurrentBook(null)}
              >
                <ArrowLeft size={16} />
                Back to Library
              </button>
              <div style={{ display: 'flex', gap: '12px' }}>
                <button className="btn btn-secondary" onClick={handleExportHtml}>
                  <Download size={16} />
                  Export HTML
                </button>
                <button className="btn btn-accent" onClick={() => window.print()}>
                  <FileText size={16} />
                  Print PDF
                </button>
              </div>
            </div>

            {/* Title Display */}
            <h2 className="text-gradient" style={{ textAlign: 'center', fontSize: '2.5rem', fontFamily: 'var(--font-book)', marginBottom: '32px' }}>
              {currentBook.title}
            </h2>

            {/* The Actual Book Page Layout */}
            <div className="book-layout">
              {/* Illustration Side */}
              <div className="book-image-side">
                {imageLoading && (
                  <div className="skeleton" style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 2 }}></div>
                )}
                <img 
                  src={imageError 
                    ? `https://robohash.org/${encodeURIComponent(currentBook.pages[currentPageIndex].illustrationPrompt)}?set=set4`
                    : getImageUrl(currentBook.pages[currentPageIndex], currentPageIndex)
                  } 
                  alt={`Page ${currentPageIndex + 1} illustration`} 
                  className="book-image"
                  onLoadStart={() => setImageLoading(true)}
                  onLoad={() => setImageLoading(false)}
                  onError={() => {
                    console.warn("Primary image failed to load, falling back to Robohash");
                    setImageError(true);
                    setImageLoading(false);
                  }}
                />
              </div>

              {/* Text Side */}
              <div className="book-text-side">
                <p className="book-story-text">
                  {currentBook.pages[currentPageIndex].storyText}
                </p>
                
                <div>
                  {/* Page Footer / Number */}
                  <div className="book-page-number">
                    Page {currentPageIndex + 1} of {currentBook.pages.length}
                  </div>
                </div>
              </div>
            </div>

            {/* Navigation & Controls */}
            <div className="no-print" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '24px' }}>
              <button 
                className="btn btn-secondary"
                disabled={currentPageIndex === 0}
                onClick={() => {
                  setCurrentPageIndex(currentPageIndex - 1);
                  setIsEditing(false);
                }}
              >
                <ArrowLeft size={16} />
                Previous Page
              </button>
              
              <div style={{ display: 'flex', gap: '12px' }}>
                <button 
                  className="btn btn-secondary"
                  onClick={handleRerollImage}
                  title="Generate a new variation of this illustration"
                >
                  <RefreshCw size={16} />
                  Re-roll Image
                </button>
                <button 
                  className="btn btn-secondary"
                  onClick={isEditing ? handleSaveChanges : startEditing}
                >
                  {isEditing ? <Check size={16} /> : <Edit2 size={16} />}
                  {isEditing ? 'Save Changes' : 'Edit Page'}
                </button>
              </div>

              <button 
                className="btn btn-secondary"
                disabled={currentPageIndex === currentBook.pages.length - 1}
                onClick={() => {
                  setCurrentPageIndex(currentPageIndex + 1);
                  setIsEditing(false);
                }}
              >
                Next Page
                <ArrowRight size={16} />
              </button>
            </div>

            {/* Editor Workspace Panel (Grows/Shrinks when open) */}
            {isEditing && (
              <div className="glass-panel editor-panel no-print" style={{ marginTop: '30px' }}>
                <h3 style={{ fontSize: '1.2rem', color: 'var(--primary)' }}>Adventure Studio Editor</h3>
                
                <div className="form-group">
                  <label className="form-label">Story Text</label>
                  <textarea 
                    className="form-textarea"
                    value={editedText}
                    onChange={(e) => setEditedText(e.target.value)}
                    style={{ minHeight: '120px' }}
                  />
                </div>

                <div className="form-group">
                  <label className="form-label">Illustration Prompt (AI Description)</label>
                  <textarea 
                    className="form-textarea"
                    value={editedPrompt}
                    onChange={(e) => setEditedPrompt(e.target.value)}
                    style={{ minHeight: '100px' }}
                  />
                  <small style={{ color: 'var(--text-muted)' }}>
                    Tip: Keep protagonist descriptions consistent for cohesive storytelling images.
                  </small>
                </div>

                <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px', marginTop: '8px' }}>
                  <button className="btn btn-secondary" onClick={() => setIsEditing(false)}>Cancel</button>
                  <button className="btn btn-primary" onClick={handleSaveChanges}>Apply Changes</button>
                </div>
              </div>
            )}
          </div>
        )}

        {/* SETUP WIZARD & LIBRARY DASHBOARD */}
        {!currentBook && !loading && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '40px' }}>
            
            {/* The Setup Panel */}
            <div className="glass-panel" style={{ padding: '32px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '24px', borderBottom: '1px solid var(--border-glass)', paddingBottom: '16px' }}>
                <Wand2 size={24} style={{ color: 'var(--accent)' }} />
                <h2 style={{ fontSize: '1.8rem', fontWeight: 600 }}>Create an Illustrated Adventure</h2>
              </div>

              <div className="wizard-grid">
                
                {/* Left Form: Theme & Protagonist */}
                <div>
                  <div className="form-group">
                    <label className="form-label">Select Adventure Theme</label>
                    <div className="theme-grid">
                      {THEME_OPTIONS.map((t) => (
                        <div 
                          key={t.id} 
                          className={`theme-card ${theme === t.id ? 'active' : ''}`}
                          onClick={() => setTheme(t.id)}
                        >
                          <div style={{ fontSize: '1.8rem', marginBottom: '6px' }}>{t.icon}</div>
                          <div style={{ fontSize: '0.85rem', fontWeight: 600 }}>{t.label.split(' ')[0]}</div>
                        </div>
                      ))}
                    </div>
                  </div>

                  {theme === 'Custom' && (
                    <div className="form-group">
                      <label className="form-label">Define Custom Illustration Style</label>
                      <input 
                        type="text" 
                        className="form-input" 
                        placeholder="e.g. colored pencil sketch, 8-bit retro art, soft claymation"
                        value={customStyle}
                        onChange={(e) => setCustomStyle(e.target.value)}
                      />
                    </div>
                  )}

                  <div className="form-group" style={{ marginTop: '20px' }}>
                    <h4 style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', borderBottom: '1px dashed var(--border-glass)', paddingBottom: '4px', marginBottom: '12px' }}>
                      Protagonist Details (Ensures Consistent Look)
                    </h4>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '12px', marginTop: '8px' }}>
                      <div className="form-group">
                        <label className="form-label">Name</label>
                        <input 
                          type="text" 
                          className="form-input" 
                          value={protagonistName} 
                          onChange={(e) => setProtagonistName(e.target.value)}
                        />
                      </div>
                      <div className="form-group">
                        <label className="form-label">Appearance (Vivid details)</label>
                        <input 
                          type="text" 
                          className="form-input" 
                          value={protagonistDescription} 
                          onChange={(e) => setProtagonistDescription(e.target.value)}
                          placeholder="e.g., small brown puppy with a red bandana"
                        />
                      </div>
                    </div>
                  </div>

                  <div className="form-group">
                    <h4 style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', borderBottom: '1px dashed var(--border-glass)', paddingBottom: '4px', marginBottom: '12px' }}>
                      Companion & Tools (Optional)
                    </h4>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '12px', marginTop: '8px' }}>
                      <div className="form-group">
                        <label className="form-label">Companion Name</label>
                        <input 
                          type="text" 
                          className="form-input" 
                          value={companionName} 
                          onChange={(e) => setCompanionName(e.target.value)} 
                          placeholder="e.g., Oliver"
                        />
                      </div>
                      <div className="form-group">
                        <label className="form-label">Companion Appearance</label>
                        <input 
                          type="text" 
                          className="form-input" 
                          value={companionDescription} 
                          onChange={(e) => setCompanionDescription(e.target.value)}
                          placeholder="e.g., fluffy grey owl with yellow eyes"
                        />
                      </div>
                    </div>
                    
                    <div className="form-group">
                      <label className="form-label">Special Item / Tool</label>
                      <input 
                        type="text" 
                        className="form-input" 
                        value={specialTool} 
                        onChange={(e) => setSpecialTool(e.target.value)}
                        placeholder="e.g., magnifying glass that glows near clues"
                      />
                    </div>
                  </div>
                </div>

                {/* Right Form: Settings & Model Choice */}
                <div>
                  <div className="form-group">
                    <label className="form-label">Story Tone</label>
                    <select className="form-select" value={tone} onChange={(e) => setTone(e.target.value)}>
                      <option value="Whimsical">Whimsical & Fairy-like</option>
                      <option value="Epic & Adventurous">Epic & Adventurous</option>
                      <option value="Mysterious & Cozy">Mysterious & Cozy</option>
                      <option value="Spooky & Thrilling">Spooky & Thrilling</option>
                      <option value="Heartwarming & Gentle">Heartwarming & Gentle</option>
                    </select>
                  </div>

                  <div className="form-group">
                    <label className="form-label">Target Age Group</label>
                    <select className="form-select" value={ageGroup} onChange={(e) => setAgeGroup(e.target.value)}>
                      <option value="3-5 years">Toddler (3-5 years) — Simple words, rhythmic text</option>
                      <option value="6-8 years">Early Reader (6-8 years) — Whimsical, engaging adventures</option>
                      <option value="9-12 years">Pre-teen (9-12 years) — Complex plots, riddle Solving</option>
                    </select>
                  </div>

                  <div className="form-group">
                    <label className="form-label">Page Count</label>
                    <select className="form-select" value={pagesCount.toString()} onChange={(e) => setPagesCount(parseInt(e.target.value))}>
                      <option value="3">3 Pages (Mini story)</option>
                      <option value="5">5 Pages (Standard)</option>
                      <option value="8">8 Pages (Extended)</option>
                      <option value="10">10 Pages (Full Adventure)</option>
                    </select>
                  </div>

                  <div className="form-group">
                    <label className="form-label">Scribe Engine (Gemini Model)</label>
                    <select className="form-select" value={model} onChange={(e) => setModel(e.target.value)}>
                      <option value="gemini-2.5-flash">Gemini 2.5 Flash (Super fast & smart)</option>
                      <option value="gemini-2.0-flash">Gemini 2.0 Flash (Stable)</option>
                      <option value="gemini-1.5-flash">Gemini 1.5 Flash (Fallback)</option>
                    </select>
                  </div>

                  <div className="form-group">
                    <label className="form-label">Illustration Style</label>
                    <select 
                      className="form-select" 
                      value={illustrationStyle} 
                      onChange={(e) => setIllustrationStyle(e.target.value as 'fairy' | 'simple_strokes')}
                    >
                      <option value="fairy">Fairy Tale / Watercolor 🎨</option>
                      <option value="simple_strokes">Simple Strokes (Minimalist Doodle) ✏️</option>
                    </select>
                  </div>

                  <div className="form-group">
                    <label className="form-label">Illustration Artist (Image Generator)</label>
                    <select className="form-select" value={imageGenerator} onChange={(e) => setImageGenerator(e.target.value as 'gemini' | 'lexica' | 'pollinations')}>
                      <option value="lexica">Lexica Art Search (Free, Fast, Turnstile-free)</option>
                      <option value="gemini">Google Gemini AI (Paid Key, Turnstile-free)</option>
                      <option value="pollinations">Pollinations AI (Free, Web-based, May rate limit)</option>
                    </select>
                  </div>

                  <div style={{ marginTop: '40px' }}>
                    <button 
                      className="btn btn-primary" 
                      onClick={handleGenerateBook}
                      style={{ width: '100%', justifyContent: 'center', padding: '16px' }}
                      disabled={loading}
                    >
                      <Sparkles size={20} />
                      Generate Adventure Book
                    </button>
                  </div>
                </div>

              </div>
            </div>

            {/* LIBRARY / PAST ADVENTURES LIST */}
            <div className="glass-panel" style={{ padding: '32px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '16px', marginBottom: '24px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <BookOpen size={24} style={{ color: 'var(--primary)' }} />
                  <h3 style={{ fontSize: '1.4rem', fontWeight: 600, margin: 0 }}>Your Storybook Library ({library.length})</h3>
                </div>
                
                <div style={{ display: 'flex', gap: '10px' }} className="no-print">
                  <button 
                    className="btn btn-secondary" 
                    style={{ padding: '6px 12px', fontSize: '0.85rem', display: 'flex', alignItems: 'center', gap: '6px' }}
                    onClick={handleExportLibraryJSON}
                    title="Backup all stories to a JSON file"
                  >
                    <Download size={14} />
                    Export Backup
                  </button>
                  
                  <label 
                    className="btn btn-secondary" 
                    style={{ padding: '6px 12px', fontSize: '0.85rem', display: 'flex', alignItems: 'center', gap: '6px', cursor: 'pointer' }}
                    title="Restore stories from a backup JSON file"
                  >
                    <Plus size={14} />
                    Import Backup
                    <input 
                      type="file" 
                      accept=".json" 
                      onChange={handleImportLibraryJSON} 
                      style={{ display: 'none' }} 
                    />
                  </label>
                </div>
              </div>

              {library.length === 0 ? (
                <div style={{ textAlign: 'center', padding: '40px', color: 'var(--text-muted)' }}>
                  <HelpCircle size={48} style={{ margin: '0 auto 16px', opacity: 0.5 }} />
                  <p>Your library is currently empty. Use the forge above to generate your first adventure!</p>
                </div>
              ) : (
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '20px' }}>
                  {library.map((book) => {
                    const themeObj = THEME_OPTIONS.find(t => t.id === book.config.theme);
                    // Use page 1 image as cover
                    const coverImageUrl = book.images && book.images[0]
                      ? book.images[0]
                      : `https://image.pollinations.ai/prompt/${encodeURIComponent(
                          book.pages[0].illustrationPrompt + ', ' + (
                            book.config.illustrationStyle === 'simple_strokes'
                              ? 'minimalist simple black ink outline sketch on a clean solid white background, cute childlike marker doodle style, simple strokes, black ink on white paper, no color, no background detail'
                              : (themeObj ? themeObj.promptStyle : 'children\'s book illustration')
                          )
                        )}?width=300&height=220&nologo=true&seed=${book.seeds[0]}`;

                    return (
                      <div 
                        key={book.id} 
                        className="glass-panel" 
                        style={{ display: 'flex', flexDirection: 'column', overflow: 'hidden', borderRadius: '12px', border: '1px solid var(--border-glass)' }}
                      >
                        <div style={{ height: '140px', overflow: 'hidden', position: 'relative', background: '#2d3748' }}>
                          <img src={coverImageUrl} alt={book.title} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                          <span style={{ position: 'absolute', top: '10px', right: '10px', background: 'rgba(7, 9, 19, 0.8)', padding: '4px 8px', borderRadius: '4px', fontSize: '0.75rem', fontWeight: 600 }}>
                            {book.pages.length} Pages
                          </span>
                        </div>
                        
                        <div style={{ padding: '16px', flexGrow: 1, display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
                          <div>
                            <h4 style={{ fontSize: '1.1rem', fontWeight: 600, marginBottom: '6px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }} title={book.title}>
                              {book.title}
                            </h4>
                            <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                              Protagonist: <strong>{book.config.protagonistName}</strong>
                            </p>
                            <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: '12px' }}>
                              Created: {book.createdAt} | Theme: {book.config.theme}
                            </p>
                          </div>

                          <div style={{ display: 'flex', gap: '8px', borderTop: '1px solid var(--border-glass)', paddingTop: '12px' }}>
                            <button 
                              className="btn btn-secondary" 
                              style={{ padding: '6px 12px', fontSize: '0.8rem', flexGrow: 1, justifyContent: 'center' }}
                              onClick={() => {
                                setCurrentBook(book);
                                setCurrentPageIndex(0);
                              }}
                            >
                              Open Book
                            </button>
                            <button 
                              className="btn btn-secondary" 
                              style={{ padding: '8px', color: '#ef4444', borderColor: 'rgba(239, 68, 68, 0.2)' }}
                              onClick={() => handleDeleteBook(book.id)}
                              title="Delete book"
                            >
                              <Trash2 size={14} />
                            </button>
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>

          </div>
        )}
      </main>

      {/* GEMINI API KEY MODAL DIALOG */}
      {showKeyModal && (
        <div className="modal-overlay no-print">
          <div className="glass-panel modal-content">
            <h3 style={{ fontSize: '1.3rem', fontWeight: 600, marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Key style={{ color: 'var(--primary)' }} />
              Gemini API Key Required
            </h3>
            
            <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: '20px' }}>
              To write stories and descriptions, this app connects directly to the official Google Gemini API. 
              Your key is saved locally in your browser and is never uploaded anywhere else.
            </p>

            <div className="form-group" style={{ marginBottom: '24px' }}>
              <label className="form-label">Input Gemini API Key</label>
              <input 
                type="password" 
                className="form-input" 
                placeholder="AIzaSy..." 
                value={tempKey}
                onChange={(e) => setTempKey(e.target.value)}
              />
              <small style={{ color: 'var(--text-muted)', display: 'block', marginTop: '4px' }}>
                Don't have a key? Get one for free at <a href="https://ai.google.dev/" target="_blank" rel="noreferrer" style={{ color: 'var(--primary)' }}>ai.google.dev</a>.
              </small>
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px' }}>
              {apiKey && (
                <button className="btn btn-secondary" onClick={() => setShowKeyModal(false)}>
                  Cancel
                </button>
              )}
              <button 
                className="btn btn-primary" 
                onClick={() => handleSaveKey(tempKey)}
                disabled={!tempKey.trim()}
              >
                Save & Continue
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
